# docker-compose para servidor teste gbdserver
version: '3.1'

services:

# mongodb server. Use root/example as user/password credentials
  mongo:
    image: mongo
    restart: always
    ports:
      - 17017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: anonymous
      MONGO_INITDB_ROOT_PASSWORD: guest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: anonymous
      ME_CONFIG_MONGODB_ADMINPASSWORD: guest

# sftp server
  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: anonymous:guest:::gbdserver


