# docker-compose para servidor teste gbdserver
version: '3.1'

services:

# mongodb server. Use root/example as user/password credentials
  mongo:
    image: mongo
    restart: always
    ports:
      - 17017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

# sftp server
  sftp:
    image: atmoz/sftp
    ports:
        - "2222:22"
    command: foo:pass:::upload


